### ISSUE TITLE
LOS 打开应用管理闪退

### ISSUE THREAD

**Issue by CaptainMorch** [Lanthanum-system-toolbox-v2/Issues#3]
概述:打开应用管理时闪退
描述:闪退
触发:侧边栏点击应用管理
可复现:是
应用版本:2.0.0B21
Root 权限授予:是
Magisk 模式:否
捐赠版:是
环境信息:
    Android:8.1.0
    API_level:27
    device:MI MIX 2
    OS:LineageOS 15.1
    Root:true
    Xposed:false
    Magisk:true
    verity:disabled
错误日志:
FATAL EXCEPTION: main
Process: xzr.La.systemtoolbox, PID: 21463
java.lang.IllegalArgumentException: path must be convex
	at android.graphics.Outline.setConvexPath(Outline.java:284)
	at android.view.ViewOutlineProvider$1.getOutline(ViewOutlineProvider.java:38)
	at android.view.View.rebuildOutline(View.java:14960)
	at android.view.View.setBackgroundBounds(View.java:19416)
	at android.view.View.drawBackground(View.java:19381)
	at android.view.View.draw(View.java:19183)
	at android.view.View.updateDisplayListIfDirty(View.java:18142)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.updateDisplayListIfDirty(View.java:18133)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.widget.ListView.drawChild(ListView.java:3590)
	at android.graphics.drawable.AdaptiveIconDrawable.getOutline(AdaptiveIconDrawable.java:387)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.widget.AbsListView.dispatchDraw(AbsListView.java:2638)
	at android.widget.ListView.dispatchDraw(ListView.java:3585)
	at android.view.View.draw(View.java:19195)
	at android.widget.AbsListView.draw(AbsListView.java:4310)
	at android.view.View.updateDisplayListIfDirty(View.java:18142)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.updateDisplayListIfDirty(View.java:18133)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.updateDisplayListIfDirty(View.java:18133)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.updateDisplayListIfDirty(View.java:18133)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.updateDisplayListIfDirty(View.java:18133)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.draw(View.java:19195)
	at android.widget.ScrollView.draw(ScrollView.java:1739)
	at android.view.View.updateDisplayListIfDirty(View.java:18142)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.updateDisplayListIfDirty(View.java:18133)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.support.v4.widget.DrawerLayout.drawChild(Unknown Source:98)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.updateDisplayListIfDirty(View.java:18133)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.updateDisplayListIfDirty(View.java:18133)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.updateDisplayListIfDirty(View.java:18133)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.updateDisplayListIfDirty(View.java:18133)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.updateDisplayListIfDirty(View.java:18133)
	at android.view.View.draw(View.java:18920)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.draw(View.java:19195)
	at com.android.internal.policy.DecorView.draw(DecorView.java:788)
	at android.view.View.updateDisplayListIfDirty(View.java:18142)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2992)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by CaptainMorch** [comment]
更新至 2.0.0B21 前也会闪退  # 当时忘记看是哪个版本了
